import Link from "next/link";
import { ArrowRight, Bell, BookOpen, ClipboardCheck, FilePlus2, Megaphone, Plus, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatDateTime } from "@/lib/classes/format";
import type { ProfessorWorkDashboard } from "@/lib/dashboard/professorWork";

export function TeacherWorkDashboard({ data }: { data: ProfessorWorkDashboard }) {
  const attention = data.pendingCorrections > 0 || data.upcoming.length > 0;
  return <div className="space-y-6">
    <section aria-labelledby="attention-title" className="rounded-xl border border-border bg-card p-5 shadow-elevated">
      <h2 id="attention-title" className="font-display text-xl font-bold text-foreground">Precisa da sua atenção</h2><p className="mt-1 text-sm text-muted-foreground">Veja o que merece prioridade hoje.</p>
      {!attention ? <div className="mt-5 rounded-lg border border-brand-border bg-brand-dim p-4"><p className="font-semibold text-foreground">Tudo em dia</p><p className="mt-1 text-sm text-muted-foreground">Você não possui correções ou prazos urgentes no momento.</p><Button className="mt-3" size="sm" asChild><Link href="/professor/provas/nova">Criar conteúdo</Link></Button></div> : <div className="mt-5 grid gap-3 lg:grid-cols-2">{data.pendingCorrections > 0 && <WorkItem icon={<ClipboardCheck aria-hidden />} title={`${data.pendingCorrections} entrega${data.pendingCorrections === 1 ? "" : "s"} aguardando correção`} detail={data.mostPendingClass ? `${data.mostPendingClass.name} · ${data.mostPendingClass.pending} pendente${data.mostPendingClass.pending === 1 ? "" : "s"}` : "Abra a central de correção"} href="/professor/correcao" action="Corrigir" />}{data.upcoming.slice(0, 2).map((item) => <WorkItem key={item.id} icon={<Bell aria-hidden />} title={item.title} detail={`${item.className} · ${item.kind} · prazo ${formatDateTime(item.dueAt)}`} href={`/professor/turmas/${item.classId}/atividades`} action="Revisar" />)}</div>}
    </section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(19rem,.8fr)]">
      <section className="rounded-xl border border-border bg-card p-5"><SectionHeading title="Correções" href="/professor/correcao" link="Ver correções" />{data.pendingCorrections > 0 ? <div className="mt-4"><p className="font-display text-3xl font-bold text-brand-text">{data.pendingCorrections} <span className="text-base text-foreground">aguardando</span></p><p className="mt-2 text-sm text-muted-foreground">{data.mostPendingClass ? `${data.mostPendingClass.name} concentra a maior parte das pendências.` : "Entregas enviadas pelos alunos."}</p><p className="mt-2 text-xs text-muted-foreground">{data.recentlyGraded} corrigida{data.recentlyGraded === 1 ? "" : "s"} nos últimos 7 dias</p><Button className="mt-4" size="sm" asChild><Link href="/professor/correcao">Continuar correção</Link></Button></div> : <p className="mt-4 text-sm text-muted-foreground">Nenhuma entrega aguardando correção.</p>}</section>
      <section className="rounded-xl border border-border bg-card p-5"><SectionHeading title="Próximas provas e atividades" href="/professor/atividades" link="Ver todas" />{data.upcoming.length ? <ul className="mt-3 space-y-2">{data.upcoming.map((item) => <li key={item.id}><Link href={`/professor/turmas/${item.classId}/atividades`} className="block rounded-md border border-border p-3 transition hover:bg-card-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-glow"><p className="truncate text-sm font-semibold text-foreground">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.className} · {item.kind} · {formatDateTime(item.dueAt)}</p></Link></li>)}</ul> : <p className="mt-4 text-sm text-muted-foreground">Nenhuma prova ou atividade com prazo próximo.</p>}</section>
    </div>
    <section aria-labelledby="classes-title"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 id="classes-title" className="font-display text-xl font-bold text-foreground">Suas turmas</h2><p className="mt-1 text-sm text-muted-foreground">Acompanhe o que está acontecendo em cada turma.</p></div><Link href="/professor/turmas" className="text-sm font-semibold text-brand-text">Ver turmas</Link></div>{data.classes.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.classes.slice(0, 3).map((item) => <Link key={item.id} href={`/professor/turmas/${item.id}`} className="rounded-xl border border-border bg-card p-4 transition hover:-translate-y-0.5 hover:border-border-hover hover:bg-card-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-glow"><h3 className="truncate font-display text-base font-bold text-foreground">{item.name}</h3><p className="mt-2 text-sm text-muted-foreground">{item.students} aluno{item.students === 1 ? "" : "s"} · {item.materials} material{item.materials === 1 ? "" : "is"}</p><p className="mt-1 text-sm text-muted-foreground">{item.pendingCorrections ? `${item.pendingCorrections} correção(ões) pendente(s)` : "Correções em dia"}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-brand-text">Abrir turma <ArrowRight className="size-3.5" aria-hidden /></span></Link>)}</div> : <div className="rounded-xl border border-dashed border-border bg-card p-6"><p className="font-semibold text-foreground">Você ainda não criou nenhuma turma.</p><Button className="mt-3" size="sm" asChild><Link href="/professor/turmas"><Plus aria-hidden />Criar turma</Link></Button></div>}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-border bg-card p-5"><SectionHeading title="Avisos" href="/professor/avisos" link="Ver avisos" />{data.latestAnnouncement ? <><p className="mt-4 line-clamp-2 whitespace-pre-wrap text-sm text-foreground">{data.latestAnnouncement.message}</p><p className="mt-2 text-xs text-muted-foreground">{data.latestAnnouncement.className} · {formatDateTime(data.latestAnnouncement.createdAt)}</p></> : <p className="mt-4 text-sm text-muted-foreground">Nenhum aviso publicado recentemente.</p>}</section><section className="rounded-xl border border-border bg-card p-5"><h2 className="font-display text-lg font-bold text-foreground">Ações rápidas</h2><div className="mt-4 grid grid-cols-2 gap-2.5 sm:grid-cols-3">{[{ href: "/professor/provas/nova", label: "Nova prova", icon: FilePlus2 }, { href: "/professor/atividades/nova", label: "Nova atividade", icon: ClipboardCheck }, { href: "/professor/turmas", label: "Nova turma", icon: Users }, { href: "/professor/avisos", label: "Avisos", icon: Megaphone }, { href: "/professor/biblioteca", label: "Biblioteca", icon: BookOpen }].map((action) => { const Icon = action.icon; return <Link key={action.href} href={action.href} className="flex min-h-20 flex-col justify-center rounded-md border border-border p-3 text-sm font-semibold text-foreground transition hover:bg-card-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-glow"><Icon className="mb-2 size-4 text-brand-text" aria-hidden />{action.label}</Link>; })}</div></section></div>
  </div>;
}
function SectionHeading({ title, href, link }: { title: string; href: string; link: string }) { return <div className="flex items-center justify-between gap-3"><h2 className="font-display text-lg font-bold text-foreground">{title}</h2><Link href={href} className="text-sm font-semibold text-brand-text">{link}</Link></div>; }
function WorkItem({ icon, title, detail, href, action }: { icon: React.ReactNode; title: string; detail: string; href: string; action: string }) { return <article className="flex min-w-0 items-start gap-3 rounded-lg border border-border p-4"><span className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-md bg-brand-dim text-brand-text">{icon}</span><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold text-foreground">{title}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{detail}</p><Link href={href} className="mt-3 inline-flex text-sm font-semibold text-brand-text hover:underline">{action}</Link></div></article>; }
