"use client";

import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AudienceSelector, ClassSelect, StudentMultiSelect, type AssignmentStudentOption } from "@/components/assignments/AssignmentAudienceFields";
import { assignContent as assign } from "../../turmas/actions";
import { Button } from "@/components/ui/button";

export function SendActivityToClass({ activityId, classes, studentsByClass }: { activityId: string; classes: { id: string; name: string }[]; studentsByClass: Record<string, AssignmentStudentOption[]> }) {
  const [open, setOpen] = useState(false); const [classId, setClassId] = useState(""); const [audienceType, setAudienceType] = useState<"class" | "students">("class"); const [selected, setSelected] = useState<string[]>([]); const [search, setSearch] = useState(""); const [dueAt, setDueAt] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition(); const router = useRouter();
  const students = studentsByClass[classId] ?? [];
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) setOpen(false); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [open, pending]);
  function submit(event: React.FormEvent) { event.preventDefault(); if (!classId) return setError("Selecione uma turma para continuar."); if (audienceType === "students" && selected.length === 0) return setError("Selecione pelo menos um aluno para continuar."); startTransition(async () => { try { await assign({ classId, contentType: "ACTIVITY", contentId: activityId, audienceType, studentIds: audienceType === "students" ? selected : [], dueAt: dueAt ? new Date(dueAt).toISOString() : null }); setOpen(false); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível enviar a atividade."); } }); }
  if (!open) return <Button type="button" onClick={() => setOpen(true)}>Enviar para turma</Button>;
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !pending) setOpen(false); }}><form onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="send-activity-title" className="max-h-[calc(100dvh-2rem)] w-full max-w-lg overflow-y-auto rounded-lg border border-border bg-card p-6 shadow-2xl"><h2 id="send-activity-title" className="font-display text-xl font-bold text-foreground">Enviar atividade</h2><div className="mt-5 flex flex-col gap-3.5"><ClassSelect classes={classes} value={classId} onValueChange={(value) => { setClassId(value); setSelected([]); setSearch(""); }} disabled={pending} /><AudienceSelector value={audienceType} onValueChange={(value) => { setAudienceType(value); if (value === "class") setSelected([]); }} disabled={pending || !classId} />{audienceType === "students" && <StudentMultiSelect students={students} selectedIds={selected} search={search} onSearchChange={setSearch} onSelectionChange={setSelected} disabled={pending || !classId} />}<label className="flex flex-col gap-1.5 text-sm font-semibold text-foreground">Prazo (opcional)<input className="rounded-md border border-input bg-transparent px-3 py-2 text-sm" type="datetime-local" value={dueAt} onChange={(event) => setDueAt(event.target.value)} disabled={pending} /></label></div>{error && <p role="alert" className="mt-3 text-sm text-danger-text">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)} disabled={pending}>Cancelar</Button><Button type="submit" disabled={pending || !classId || (audienceType === "students" && selected.length === 0)}>{pending ? "Enviando…" : "Confirmar envio"}</Button></div></form></div>;
}
