"use client";
import { useState } from "react";
import { normalizeBnccCodes } from "@/lib/questions/bncc";
import { MAX_QUESTION_TAG_LENGTH, MAX_QUESTION_TAGS, normalizeQuestionTags } from "@/lib/questions/tags";

export function QuestionMetadataFields({ tags, bnccCodes, onTagsChange, onBnccCodesChange, idPrefix = "question" }: { tags: string[]; bnccCodes: string[]; onTagsChange: (tags: string[]) => void; onBnccCodesChange: (codes: string[]) => void; idPrefix?: string }) {
  const [tag, setTag] = useState(""); const [code, setCode] = useState(""); const [error, setError] = useState<string | null>(null);
  function addTag() { try { const next = normalizeQuestionTags([...tags, tag]) ?? []; if (next.length === tags.length) return; onTagsChange(next); setTag(""); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Tag invalida."); } }
  function addCode() { try { const next = normalizeBnccCodes([...bnccCodes, code]) ?? []; if (next.length === bnccCodes.length) return; onBnccCodesChange(next); setCode(""); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Codigo BNCC invalido."); } }
  return <div className="grid grid-cols-1 gap-3.5 min-[861px]:grid-cols-2">
    <div className="flex flex-col gap-1.5"><label htmlFor={`${idPrefix}-tags`} className="text-sm font-semibold text-foreground">Tags</label><input id={`${idPrefix}-tags`} value={tag} maxLength={MAX_QUESTION_TAG_LENGTH} placeholder="Digite e pressione Enter" onChange={(e) => setTag(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" || e.key === ",") { e.preventDefault(); addTag(); } }} className="w-full rounded-sm border border-border bg-[rgba(var(--overlay-rgb),0.04)] px-3 py-2.5 text-md outline-none focus:border-brand-border focus:ring-[3px] focus:ring-brand-glow" /><span className="text-xs text-muted-foreground">Até {MAX_QUESTION_TAGS} tags.</span><div className="flex flex-wrap gap-1.5">{tags.map((item) => <span key={item.toLowerCase()} className="rounded-full border border-border bg-brand-dim px-2 py-1 text-xs">{item}<button type="button" className="ml-1" aria-label={`Remover tag ${item}`} onClick={() => onTagsChange(tags.filter((value) => value.toLowerCase() !== item.toLowerCase()))}>×</button></span>)}</div></div>
    <div className="flex flex-col gap-1.5"><label htmlFor={`${idPrefix}-bncc`} className="text-sm font-semibold text-foreground">Habilidade BNCC</label><input id={`${idPrefix}-bncc`} value={code} placeholder="EF06MA07" onChange={(e) => setCode(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" || e.key === ",") { e.preventDefault(); addCode(); } }} className="w-full rounded-sm border border-border bg-[rgba(var(--overlay-rgb),0.04)] px-3 py-2.5 text-md uppercase outline-none focus:border-brand-border focus:ring-[3px] focus:ring-brand-glow" /><span className="text-xs text-muted-foreground">Código validado e salvo na tabela BNCC existente.</span><div className="flex flex-wrap gap-1.5">{bnccCodes.map((item) => <span key={item} className="rounded-full border border-border px-2 py-1 text-xs">{item}<button type="button" className="ml-1" aria-label={`Remover codigo BNCC ${item}`} onClick={() => onBnccCodesChange(bnccCodes.filter((value) => value !== item))}>×</button></span>)}</div></div>
    {error && <p role="alert" className="text-sm text-danger-text min-[861px]:col-span-2">{error}</p>}
  </div>;
}
